Fix compile error about missing QStringView overload
Prevents the following compiler error:
```
/build/mingw-w64-qt6-activeqt/src/qtactiveqt-everywhere-src-6.3.2/tools/dumpcpp/main.cpp:599:41: error: no match for ‘operator+’ (operand types are ‘const QString’ and ‘QStringView’)
  599 |             moCode.insert(startType, ns + QStringView(u"::"));
      |                                      ~~ ^ ~~~~~~~~~~~~~~~~~~
      |                                      |    |
      |                                      |    QStringView
      |                                      const QString
```